#!/usr/bin/env bash
set -eu
# see https://www.micro-manager.org/wiki/Build_on_MacOS_X#Getting_Micro-Manager_source_code
# and https://www.micro-manager.org/wiki/Download%20Micro-Manager_Latest%20Release

# Configuration variables
fijidir="${fijidir:-/Applications/Fiji.app}"
port=4000
patchdir=$(cd $(dirname "$0")/../patches && pwd)

# install dependencies on mac using homebrew
if [[ -z $(command -v brew) ]]; then
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
fi
brew tap homebrew/science
brew install autoconf automake libtool pkg-config swig subversion boost libusb-compat hidapi libdc1394 libgphoto2 freeimage opencv python numpy git maven ant msgpack
brew cask install java

# install fiji on mac
wget http://jenkins.imagej.net/job/Stable-Fiji-MacOSX/lastSuccessfulBuild/artifact/fiji-macosx.dmg
hdiutil attach fiji-macosx.dmg
if test -e "$fijidir"; then 
  rm -rv "$fijidir"
fi
cp -Rv /Volumes/Fiji/Fiji.app "$fijidir"
hdiutil detach /Volumes/Fiji
rm -v fiji-macosx.dmg

# add remote debugging support to Info.plist
cd "$fijidir"
defaults write "$PWD"/Contents/Info fiji -dict-add JVMOptions "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=$port"
plutil -convert xml1 Contents/Info.plist
cd -

#install micro-manager from source
#export JAVA_HOME=$(/usr/libexec/java_home)
mkdir -pv micromanager
cd micromanager
svn --username guest --password guest checkout https://valelab.ucsf.edu/svn/micromanager2/trunk micromanager
mkdir -pv 3rdpartypublic
svn --username guest --password guest checkout https://valelab.ucsf.edu/svn/3rdpartypublic/classext 3rdpartypublic/classext
cd micromanager
./autogen.sh
./configure --enable-imagej-plugin="$fijidir" --with-ij-jar="$(echo "$fijidir"/jars/ij*.jar)"
make fetchdeps
# apply patches
patch -p0 <"$patchdir"/disable-disk-space-check.patch
make -j
make install
