#!/usr/bin/env bash
set -eu -o pipefail
sambashare=smb://mmwin.dhcp.lbl.gov/mmwin
mmdir="/Volumes/mmwin/Program Files (x86)/Micro-Manager1.4"
fijidir="/Volumes/mmwin/Users/insitu/Desktop/Fiji32"
arch=win32
updatesite=micromanager-$arch

osascript -e "mount volume \"$sambashare\""

cd "$mmdir"
mkdir -pv "$fijidir"/mm/"$arch"
rsync -avR macros mmautofocus mmplugins plugins/Micro-Manager scripts "$fijidir"
rsync -av MMConfig_demo.cfg "$fijidir"/mm
rsync -av MMCorePy.py MMCoreWrapDemo.py *.dll *.pyd OlympusIX3Control OlympusIX3Control/ "$fijidir"/mm/"$arch"

cd "$fijidir"
# remove the ssh plugin to work around bug in imagej updater
rm -v jars/imagej-plugins-uploader-ssh-*.jar
# create update site
java -jar ./jars/imagej-updater-*.jar add-update-site "$updatesite" http://fruitfly.org/openhicamm/"$updatesite" bbooth@sina.lbl.gov /www/fruitfly.org_80/www/htdocs/openhicamm/"$updatesite"
# add files to update site
java -jar ./jars/imagej-updater-*.jar upload-complete-site --force --force-shadow "$updatesite"
