#!/usr/bin/env bash
set -eu -o pipefail
mmdir=/Applications/Micro-Manager1.4
fijidir=/Applications/Fiji.app
arch=macosx
updatesite=micromanager-"$arch"

#updateurl=http://fruitfly.org/openhicamm/micromanager-macosx
#updatessh=bbooth@sina.lbl.gov 
#updatesshpath=/www/fruitfly.org_80/www/htdocs/openhicamm/micromanager-macosx
#./Contents/MacOS/Imagej-macosx --update add-update-site "$updatesite" "$updateurl"  "$updatessh" "$updatesshpath"

cd "$mmdir"
mkdir -pv "$fijidir"/mm/"$arch"
rsync -avR luts macros mmautofocus mmplugins plugins/Micro-Manager scripts "$fijidir"
rsync -av MMConfig_demo.cfg "$fijidir"/mm
rsync -av MMCorePy.py MMCoreWrapDemo.py _MMCorePy.so libMMCoreJ_wrap.jnilib libgphoto2 libmmgr_dal_* "$fijidir"/mm/"$arch"
defaults write "$fijidir"/Contents/Info LSEnvironment -dict-add CAMLIBS mm/"$arch"/libgphoto2/libgphoto2 IOLIBS mm/"$arch"/libgphoto2/libgphoto2_port
plutil -convert xml1 "$fijidir"/Contents/Info.plist

cd "$fijidir"
# remove the ssh plugin to work around bug in imagej updater
rm -v jars/imagej-plugins-uploader-ssh-*.jar
./Contents/MacOS/Imagej-macosx --update upload-complete-site --force --force-shadow "$updatesite"
