#!/usr/bin/env bash
# make sure to add user to the dialout group: sudo usermod -a -G dialout "$USER"
fijidir=$HOME/src/Fiji.app
if [[ $(uname -ms) == 'Linux x86_64' ]]; then
  arch=linux64
elif [[ $(uname -ms) == 'Linux i686' ]]; then
  arch=linux32
else
  arch=linux
fi
updatesite=micromanager-$arch

source "$(dirname "$0")"/install-fiji-micromanager

cd "$fijidir"
"$(dirname "$0")"/copy-libs-linux |bash -x
rm -v lib* MMCorePy.py _MMCorePy.so mm/"$arch"/ImageJ-linux
mv -v mmimagej mm

# remove conflicting dependency
rm -v plugins/Micro-Manager/scijava-common-*.jar

# remove the ssh plugin to work around bug in imagej updater
rm -v jars/imagej-plugins-uploader-ssh-*.jar
java -jar ./jars/imagej-updater-*.jar upload-complete-site --force --force-shadow "$updatesite"
