CREATE TABLE PUBLIC."WORKFLOWMODULE"(
  "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) NOT NULL PRIMARY KEY,
  "NAME" VARCHAR(16777216) NOT NULL,
  "CLASSNAME" VARCHAR(16777216) NOT NULL,
  "PARENTID" INTEGER,
  "PRIORITY" INTEGER NOT NULL,
  UNIQUE("NAME")
);
* *DSV_COL_SPLITTER = \t
* *DSV_TARGET_TABLE = workflowmodule
\mq ../Workflow.txt
commit;

\h

select wm.name,
  mc.key,
  mc.value
from moduleconfig mc,
  workflowmodule wm
where mc.id=wm.id
  and mc.key in ('startTime','endTime','duration')
order by priority, 2 desc; |~/src/OpenHiCAMM/scripts/html2csv >~bbooth/Public/crm26-30.stats.csv

select ps.cartridgeposition,
  ps.slideposition,
  s.experimentid,
  wm.name as module_name,
  t2.value as positions,
  t3.value as rois,
  t4.value as acquisition_duration,
  t5.value as autofocus_duration
from task tt
join workflowmodule wm
  on wm.id=tt.moduleid
join taskconfig t
  on tt.id=t.id
  and t.key='slideId'
join slide s
  on s.id=cast(t.value as int)
join poolslide ps
  on ps.slideid=s.id
join taskconfig t2
  on t.id=t2.id
  and t2.key='positions'
join taskconfig t3
  on t.id=t3.id
  and t3.key='ROIs'
join taskconfig t4
  on t.id=t4.id
  and t4.key='acquisitionDuration'
left join taskconfig t5
  on t.id=t5.id
  and t5.key='autofocusDuration'
order by 1,2,priority; |~/src/OpenHiCAMM/scripts/html2csv >>~bbooth/Public/crm26-30.stats.csv

\h
