#!/usr/bin/env bash
comm -2 -3 <(dpkg --get-selections |perl -ple 's/\s+\S+$//' |sort |uniq) <(wget -q -O- http://releases.ubuntu.com/14.04/ubuntu-14.04.4-desktop-i386.manifest |perl -nle '/^(\S+)/ && print $1' |sort |uniq) |perl -nle '/^linux-|virtualbox|patchelf|vim|chromium|apt-rdepends|apt-file|^dkms$/ || print' |xargs sudo apt-get remove -y
sudo apt-get install -y subversion git cpanminus libterm-readline-gnu-perl libstring-shellquote-perl
